# Copyright (C) 2016 The Pure Nexus Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and

PRODUCT_COPY_FILES += \
    vendor/moto/shamu/proprietary/bin/adspd:system/bin/adspd \
    vendor/moto/shamu/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/moto/shamu/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/moto/shamu/proprietary/bin/cnd:system/bin/cnd \
    vendor/moto/shamu/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/moto/shamu/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/moto/shamu/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/moto/shamu/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/moto/shamu/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/moto/shamu/proprietary/bin/ks:system/bin/ks \
    vendor/moto/shamu/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/moto/shamu/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/moto/shamu/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/moto/shamu/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/moto/shamu/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/moto/shamu/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/moto/shamu/proprietary/bin/qmi_motext_hook:system/bin/qmi_motext_hook \
    vendor/moto/shamu/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/moto/shamu/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/moto/shamu/proprietary/bin/radish:system/bin/radish \
    vendor/moto/shamu/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/moto/shamu/proprietary/bin/tcmd_mini:system/bin/tcmd_mini \
    vendor/moto/shamu/proprietary/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/moto/shamu/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/moto/shamu/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/moto/shamu/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/moto/shamu/proprietary/etc/diag/mdm/audio_voice_apr.cfg:system/etc/diag/mdm/audio_voice_apr.cfg \
    vendor/moto/shamu/proprietary/etc/diag/mdm/Connection_Issues_V6+DPL+UIM.cfg:system/etc/diag/mdm/Connection_Issues_V6+DPL+UIM.cfg \
    vendor/moto/shamu/proprietary/etc/diag/mdm/FIT_V16_1.cfg:system/etc/diag/mdm/FIT_V16_1.cfg \
    vendor/moto/shamu/proprietary/etc/diag/mdm/FIT_V16_2_volte_full_ip.cfg:system/etc/diag/mdm/FIT_V16_2_volte_full_ip.cfg \
    vendor/moto/shamu/proprietary/etc/diag/mdm/FIT_V16_3_audio.cfg:system/etc/diag/mdm/FIT_V16_3_audio.cfg \
    vendor/moto/shamu/proprietary/etc/diag/mdm/sensors_qxdm.cfg:system/etc/diag/mdm/sensors_qxdm.cfg \
    vendor/moto/shamu/proprietary/etc/diag/mdm/voice-call-min-log.cfg:system/etc/diag/mdm/voice-call-min-log.cfg \
    vendor/moto/shamu/proprietary/etc/diag/audio_voice_apr.cfg:system/etc/diag/audio_voice_apr.cfg \
    vendor/moto/shamu/proprietary/etc/diag/sensors_qxdm.cfg:system/etc/diag/sensors_qxdm.cfg \
    vendor/moto/shamu/proprietary/etc/diag/voice-call-min-log.cfg:system/etc/diag/voice-call-min-log.cfg \
    vendor/moto/shamu/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/moto/shamu/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/moto/shamu/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/moto/shamu/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/moto/shamu/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b00:system/etc/firmware/vpu.b00 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b01:system/etc/firmware/vpu.b01 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b02:system/etc/firmware/vpu.b02 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b03:system/etc/firmware/vpu.b03 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b04:system/etc/firmware/vpu.b04 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b05:system/etc/firmware/vpu.b05 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b06:system/etc/firmware/vpu.b06 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b07:system/etc/firmware/vpu.b07 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b08:system/etc/firmware/vpu.b08 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b09:system/etc/firmware/vpu.b09 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b10:system/etc/firmware/vpu.b10 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b11:system/etc/firmware/vpu.b11 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.b12:system/etc/firmware/vpu.b12 \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.mbn:system/etc/firmware/vpu.mbn \
    vendor/moto/shamu/proprietary/etc/firmware/vpu.mdt:system/etc/firmware/vpu.mdt \
    vendor/moto/shamu/proprietary/etc/permissions/com.android.omadm.service.xml:system/etc/permissions/com.android.omadm.service.xml \
    vendor/moto/shamu/proprietary/etc/permissions/com.motorola.DirectedSMSProxy.xml:system/etc/permissions/com.motorola.DirectedSMSProxy.xml \
    vendor/moto/shamu/proprietary/etc/permissions/com.motorola.triggerenroll.xml:system/etc/permissions/com.motorola.triggerenroll.xml \
    vendor/moto/shamu/proprietary/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml:system/etc/permissions/com.verizon.hardware.telephony.ehrpd.xml \
    vendor/moto/shamu/proprietary/etc/permissions/com.verizon.hardware.telephony.lte.xml:system/etc/permissions/com.verizon.hardware.telephony.lte.xml \
    vendor/moto/shamu/proprietary/etc/permissions/com.verizon.ims.xml:system/etc/permissions/com.verizon.ims.xml \
    vendor/moto/shamu/proprietary/etc/permissions/com.vzw.vzwapnlib.xml:system/etc/permissions/com.vzw.vzwapnlib.xml \
    vendor/moto/shamu/proprietary/etc/permissions/rcsimssettings.xml:system/etc/permissions/rcsimssettings.xml \
    vendor/moto/shamu/proprietary/etc/permissions/rcsservice.xml:system/etc/permissions/rcsservice.xml \
    vendor/moto/shamu/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf \
    vendor/moto/shamu/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/moto/shamu/proprietary/etc/flp.conf:system/etc/flp.conf \
    vendor/moto/shamu/proprietary/etc/fmas_eq.dat:system/etc/fmas_eq.dat \
    vendor/moto/shamu/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/moto/shamu/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/moto/shamu/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/moto/shamu/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/moto/shamu/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/moto/shamu/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/moto/shamu/proprietary/lib/hw/audio.motvr.default.so:system/lib/hw/audio.motvr.default.so \
    vendor/moto/shamu/proprietary/lib/hw/sound_trigger.primary.shamu.so:system/lib/hw/sound_trigger.primary.shamu.so \
    vendor/moto/shamu/proprietary/lib/libadspd-jni.so:system/lib/libadspd-jni.so \
    vendor/moto/shamu/proprietary/lib/libadspd.so:system/lib/libadspd.so \
    vendor/moto/shamu/proprietary/lib/libdetectmodem.so:system/lib/libdetectmodem.so \
    vendor/moto/shamu/proprietary/lib/libdmengine.so:system/lib/libdmengine.so \
    vendor/moto/shamu/proprietary/lib/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
    vendor/moto/shamu/proprietary/lib/libflacencoder.so:system/lib/libflacencoder.so \
    vendor/moto/shamu/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/moto/shamu/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/moto/shamu/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/moto/shamu/proprietary/lib/libmotaudioutils.so:system/lib/libmotaudioutils.so \
    vendor/moto/shamu/proprietary/lib/librecoglib.so:system/lib/librecoglib.so \
    vendor/moto/shamu/proprietary/lib/libsupermodel.so:system/lib/libsupermodel.so \
    vendor/moto/shamu/proprietary/lib/libtrainingcheck.so:system/lib/libtrainingcheck.so \
    vendor/moto/shamu/proprietary/media/audio/alarms/AAAAAAAAAAAAAAAGH!!!!.ogg:system/media/audio/alarms/AAAAAAAAAAAAAAAGH!!!!.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/ArmyWakeUp.ogg:system/media/audio/alarms/ArmyWakeUp.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/DawnChorus.ogg:system/media/audio/alarms/DawnChorus.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Daybreak.ogg:system/media/audio/alarms/Daybreak.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/DrAlarm.ogg:system/media/audio/alarms/DrAlarm.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Feverfew.flac:system/media/audio/alarms/Feverfew.flac \
    vendor/moto/shamu/proprietary/media/audio/alarms/Foxglove.flac:system/media/audio/alarms/Foxglove.flac \
    vendor/moto/shamu/proprietary/media/audio/alarms/KHAlarm.ogg:system/media/audio/alarms/KHAlarm.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/MAKEITSTAHP.ogg:system/media/audio/alarms/MAKEITSTAHP.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/MusicBox.ogg:system/media/audio/alarms/MusicBox.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/NewDay.ogg:system/media/audio/alarms/NewDay.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Osmium.ogg:system/media/audio/alarms/Osmium.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Oxygen.ogg:system/media/audio/alarms/Oxygen.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/ResidentAlarm.ogg:system/media/audio/alarms/ResidentAlarm.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/ResidentEvil.ogg:system/media/audio/alarms/ResidentEvil.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Serenity.ogg:system/media/audio/alarms/Serenity.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Surreal.ogg:system/media/audio/alarms/Surreal.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/The_secret_forest.ogg:system/media/audio/alarms/The_secret_forest.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Valkyries.ogg:system/media/audio/alarms/Valkyries.ogg \
    vendor/moto/shamu/proprietary/media/audio/alarms/Wisteria.flac:system/media/audio/alarms/Wisteria.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/004.ogg:system/media/audio/notifications/004.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/006.ogg:system/media/audio/notifications/006.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/008.ogg:system/media/audio/notifications/008.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/1up.ogg:system/media/audio/notifications/1up.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/3dsms.ogg:system/media/audio/notifications/3dsms.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Amaranth.flac:system/media/audio/notifications/Amaranth.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/AngryBird.ogg:system/media/audio/notifications/AngryBird.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Ariel.ogg:system/media/audio/notifications/Ariel.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/BOOTES.ogg:system/media/audio/notifications/BOOTES.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Babylon.mp3:system/media/audio/notifications/Babylon.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/Backstay.mp3:system/media/audio/notifications/Backstay.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/BlowOffValve.ogg:system/media/audio/notifications/BlowOffValve.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Boxwood.flac:system/media/audio/notifications/Boxwood.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Button.flac:system/media/audio/notifications/Button.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Camellia.flac:system/media/audio/notifications/Camellia.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Carme.ogg:system/media/audio/notifications/Carme.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Ceres.ogg:system/media/audio/notifications/Ceres.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Chopsticks.ogg:system/media/audio/notifications/Chopsticks.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Clover.flac:system/media/audio/notifications/Clover.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/CoinDrop.ogg:system/media/audio/notifications/CoinDrop.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/CoolSms.ogg:system/media/audio/notifications/CoolSms.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Cutie.mp3:system/media/audio/notifications/Cutie.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/Dalek.ogg:system/media/audio/notifications/Dalek.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/DubstepSms.ogg:system/media/audio/notifications/DubstepSms.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/DukesOfHazard.ogg:system/media/audio/notifications/DukesOfHazard.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Elara.ogg:system/media/audio/notifications/Elara.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Europa.ogg:system/media/audio/notifications/Europa.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/FF.ogg:system/media/audio/notifications/FF.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Flip_Phone.mp3:system/media/audio/notifications/Flip_Phone.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/Foxtail.flac:system/media/audio/notifications/Foxtail.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Freesia.flac:system/media/audio/notifications/Freesia.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/GameOverGuitar.ogg:system/media/audio/notifications/GameOverGuitar.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/GermanCow.ogg:system/media/audio/notifications/GermanCow.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Halo.ogg:system/media/audio/notifications/Halo.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Heather.flac:system/media/audio/notifications/Heather.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/HeyListen.ogg:system/media/audio/notifications/HeyListen.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/HungerGames.ogg:system/media/audio/notifications/HungerGames.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/ISeeYou.ogg:system/media/audio/notifications/ISeeYou.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Iapetus.ogg:system/media/audio/notifications/Iapetus.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Indigo.flac:system/media/audio/notifications/Indigo.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Io.ogg:system/media/audio/notifications/Io.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/JarvisMessage.ogg:system/media/audio/notifications/JarvisMessage.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/LSecret.ogg:system/media/audio/notifications/LSecret.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Lilac.flac:system/media/audio/notifications/Lilac.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Lily.flac:system/media/audio/notifications/Lily.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Lotus.flac:system/media/audio/notifications/Lotus.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Lupine.flac:system/media/audio/notifications/Lupine.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/MIB.ogg:system/media/audio/notifications/MIB.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/MarioDie.ogg:system/media/audio/notifications/MarioDie.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/MarioJump.ogg:system/media/audio/notifications/MarioJump.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/MarioPowerUp.ogg:system/media/audio/notifications/MarioPowerUp.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/MessageReceived2.ogg:system/media/audio/notifications/MessageReceived2.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/MinionLaugh.ogg:system/media/audio/notifications/MinionLaugh.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Mira.ogg:system/media/audio/notifications/Mira.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Notif.ogg:system/media/audio/notifications/Notif.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/OldSpice.ogg:system/media/audio/notifications/OldSpice.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Orchid.flac:system/media/audio/notifications/Orchid.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/PacManDies.ogg:system/media/audio/notifications/PacManDies.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Perl_Drop.mp3:system/media/audio/notifications/Perl_Drop.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/Peter.ogg:system/media/audio/notifications/Peter.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Procyon.ogg:system/media/audio/notifications/Procyon.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Proxima.ogg:system/media/audio/notifications/Proxima.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/PstPstPst.ogg:system/media/audio/notifications/PstPstPst.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Quince.flac:system/media/audio/notifications/Quince.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Rhea.ogg:system/media/audio/notifications/Rhea.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Bubbles.ogg:system/media/audio/notifications/S_Bubbles.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Buubles.ogg:system/media/audio/notifications/S_Buubles.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Charming_bell.ogg:system/media/audio/notifications/S_Charming_bell.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Dew_drops.ogg:system/media/audio/notifications/S_Dew_drops.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Flowers.ogg:system/media/audio/notifications/S_Flowers.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Good_News.ogg:system/media/audio/notifications/S_Good_News.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Haze.ogg:system/media/audio/notifications/S_Haze.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Knock.ogg:system/media/audio/notifications/S_Knock.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_On_time.ogg:system/media/audio/notifications/S_On_time.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Opener.ogg:system/media/audio/notifications/S_Opener.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/S_Pure_Bell.ogg:system/media/audio/notifications/S_Pure_Bell.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Sage.flac:system/media/audio/notifications/Sage.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Salacia.ogg:system/media/audio/notifications/Salacia.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Salvia.flac:system/media/audio/notifications/Salvia.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/SamuraiSword.ogg:system/media/audio/notifications/SamuraiSword.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/ScreamingGoat.ogg:system/media/audio/notifications/ScreamingGoat.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Scry.mp3:system/media/audio/notifications/Scry.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/Sorrel.flac:system/media/audio/notifications/Sorrel.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Squeeky.ogg:system/media/audio/notifications/Squeeky.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Suweet.ogg:system/media/audio/notifications/Suweet.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/SweetBrownNotif7.ogg:system/media/audio/notifications/SweetBrownNotif7.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Tardis.ogg:system/media/audio/notifications/Tardis.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/TardisLanding.ogg:system/media/audio/notifications/TardisLanding.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Tejat.ogg:system/media/audio/notifications/Tejat.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Tethys.ogg:system/media/audio/notifications/Tethys.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Titan.ogg:system/media/audio/notifications/Titan.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Transformer.ogg:system/media/audio/notifications/Transformer.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Twoosh.mp3:system/media/audio/notifications/Twoosh.mp3 \
    vendor/moto/shamu/proprietary/media/audio/notifications/Verbena.flac:system/media/audio/notifications/Verbena.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/W8.ogg:system/media/audio/notifications/W8.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Watsonia.flac:system/media/audio/notifications/Watsonia.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/Wi-fi.ogg:system/media/audio/notifications/Wi-fi.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Willow.flac:system/media/audio/notifications/Willow.flac \
    vendor/moto/shamu/proprietary/media/audio/notifications/YesMaster.ogg:system/media/audio/notifications/YesMaster.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/ZeldaKey.ogg:system/media/audio/notifications/ZeldaKey.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/Zoom.ogg:system/media/audio/notifications/Zoom.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/bark2.ogg:system/media/audio/notifications/bark2.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/bass.ogg:system/media/audio/notifications/bass.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/burp.ogg:system/media/audio/notifications/burp.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/chimes.ogg:system/media/audio/notifications/chimes.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/click.ogg:system/media/audio/notifications/click.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/hangup.ogg:system/media/audio/notifications/hangup.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/harp.ogg:system/media/audio/notifications/harp.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/hat.ogg:system/media/audio/notifications/hat.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/hp.ogg:system/media/audio/notifications/hp.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/lo.ogg:system/media/audio/notifications/lo.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/meow1.ogg:system/media/audio/notifications/meow1.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/meow2.ogg:system/media/audio/notifications/meow2.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/meow3.ogg:system/media/audio/notifications/meow3.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/meow4.ogg:system/media/audio/notifications/meow4.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/moan5.ogg:system/media/audio/notifications/moan5.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/moan6.ogg:system/media/audio/notifications/moan6.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/moan7.ogg:system/media/audio/notifications/moan7.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/orb.ogg:system/media/audio/notifications/orb.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/pixiedust.ogg:system/media/audio/notifications/pixiedust.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/portal.ogg:system/media/audio/notifications/portal.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/portal2.ogg:system/media/audio/notifications/portal2.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/power_ranger_Communicator_Beeps.ogg:system/media/audio/notifications/power_ranger_Communicator_Beeps.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/pray.ogg:system/media/audio/notifications/pray.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/present.ogg:system/media/audio/notifications/present.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/psi.ogg:system/media/audio/notifications/psi.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/r2d2text.ogg:system/media/audio/notifications/r2d2text.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/spooky.ogg:system/media/audio/notifications/spooky.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/starstorm.ogg:system/media/audio/notifications/starstorm.ogg \
    vendor/moto/shamu/proprietary/media/audio/notifications/win.ogg:system/media/audio/notifications/win.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/02_Fog_on_the_water.ogg:system/media/audio/ringtones/02_Fog_on_the_water.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/04_Blowing_dandelion_seeds.ogg:system/media/audio/ringtones/04_Blowing_dandelion_seeds.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/29_Gentle_spring_rain.ogg:system/media/audio/ringtones/29_Gentle_spring_rain.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/3dRing.ogg:system/media/audio/ringtones/3dRing.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Alice.ogg:system/media/audio/ringtones/Alice.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Amaryllis.flac:system/media/audio/ringtones/Amaryllis.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Amplifier.ogg:system/media/audio/ringtones/Amplifier.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Anise.flac:system/media/audio/ringtones/Anise.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/AnotherRomanceGuitar.ogg:system/media/audio/ringtones/AnotherRomanceGuitar.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/ArRehman.ogg:system/media/audio/ringtones/ArRehman.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Aster.flac:system/media/audio/ringtones/Aster.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/BackInBlack.ogg:system/media/audio/ringtones/BackInBlack.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Bergamot.flac:system/media/audio/ringtones/Bergamot.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Callisto.ogg:system/media/audio/ringtones/Callisto.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Caraway.flac:system/media/audio/ringtones/Caraway.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Caspia.flac:system/media/audio/ringtones/Caspia.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Chicory.flac:system/media/audio/ringtones/Chicory.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Crank.ogg:system/media/audio/ringtones/Crank.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Curcuma.flac:system/media/audio/ringtones/Curcuma.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Curve.ogg:system/media/audio/ringtones/Curve.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Dahlia.flac:system/media/audio/ringtones/Dahlia.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Dione.ogg:system/media/audio/ringtones/Dione.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Diosma.flac:system/media/audio/ringtones/Diosma.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/DroidKillsIphone.ogg:system/media/audio/ringtones/DroidKillsIphone.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Eureka.ogg:system/media/audio/ringtones/Eureka.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/FFS.ogg:system/media/audio/ringtones/FFS.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/FullBass.ogg:system/media/audio/ringtones/FullBass.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Funny.ogg:system/media/audio/ringtones/Funny.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/FuturePhoneRing.ogg:system/media/audio/ringtones/FuturePhoneRing.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Galaxy.ogg:system/media/audio/ringtones/Galaxy.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Ganymede.ogg:system/media/audio/ringtones/Ganymede.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Gentian.flac:system/media/audio/ringtones/Gentian.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Ghosts-Neo.ogg:system/media/audio/ringtones/Ghosts-Neo.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Glacial_Groove.ogg:system/media/audio/ringtones/Glacial_Groove.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Gladiola.flac:system/media/audio/ringtones/Gladiola.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Godfather.ogg:system/media/audio/ringtones/Godfather.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/HeartTouching.ogg:system/media/audio/ringtones/HeartTouching.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Jasmine.flac:system/media/audio/ringtones/Jasmine.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Juniper.flac:system/media/audio/ringtones/Juniper.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Larkspur.flac:system/media/audio/ringtones/Larkspur.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Lasers.ogg:system/media/audio/ringtones/Lasers.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Lovable.mp3:system/media/audio/ringtones/Lovable.mp3 \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Lumex.flac:system/media/audio/ringtones/Lumex.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Luna.ogg:system/media/audio/ringtones/Luna.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Mimosa.flac:system/media/audio/ringtones/Mimosa.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Missionimpossible.ogg:system/media/audio/ringtones/Missionimpossible.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Mum.flac:system/media/audio/ringtones/Mum.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/NFS.ogg:system/media/audio/ringtones/NFS.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/NeoBeat.ogg:system/media/audio/ringtones/NeoBeat.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Nerine.flac:system/media/audio/ringtones/Nerine.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Oberon.ogg:system/media/audio/ringtones/Oberon.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Orion.ogg:system/media/audio/ringtones/Orion.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Paintbrush.flac:system/media/audio/ringtones/Paintbrush.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Phlox.flac:system/media/audio/ringtones/Phlox.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Phobos.ogg:system/media/audio/ringtones/Phobos.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Romantic.ogg:system/media/audio/ringtones/Romantic.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Safflower.flac:system/media/audio/ringtones/Safflower.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Saffron.flac:system/media/audio/ringtones/Saffron.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Saxo.ogg:system/media/audio/ringtones/Saxo.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Sedna.ogg:system/media/audio/ringtones/Sedna.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/SickDubstep.ogg:system/media/audio/ringtones/SickDubstep.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Silver_Lining.mp3:system/media/audio/ringtones/Silver_Lining.mp3 \
    vendor/moto/shamu/proprietary/media/audio/ringtones/SmokeWaterIntro.ogg:system/media/audio/ringtones/SmokeWaterIntro.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/SpanishGuitar.ogg:system/media/audio/ringtones/SpanishGuitar.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Spearmint.flac:system/media/audio/ringtones/Spearmint.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Titania.ogg:system/media/audio/ringtones/Titania.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Triton.ogg:system/media/audio/ringtones/Triton.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Tron.ogg:system/media/audio/ringtones/Tron.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Umbriel.ogg:system/media/audio/ringtones/Umbriel.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/VZW_Airwaves_1.mp3:system/media/audio/ringtones/VZW_Airwaves_1.mp3 \
    vendor/moto/shamu/proprietary/media/audio/ringtones/VanityAngel.ogg:system/media/audio/ringtones/VanityAngel.ogg \
    vendor/moto/shamu/proprietary/media/audio/ringtones/Yarrow.flac:system/media/audio/ringtones/Yarrow.flac \
    vendor/moto/shamu/proprietary/media/audio/ringtones/matrix_phone_ring.mp3:system/media/audio/ringtones/matrix_phone_ring.mp3 \
    vendor/moto/shamu/proprietary/media/audio/ringtones/moon_light.ogg:system/media/audio/ringtones/moon_light.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/Effect_Tick.ogg:system/media/audio/ui/Effect_Tick.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/KeypressDelete.ogg:system/media/audio/ui/KeypressDelete.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/KeypressReturn.ogg:system/media/audio/ui/KeypressReturn.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/KeypressSpacebar.ogg:system/media/audio/ui/KeypressSpacebar.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/KeypressStandard.ogg:system/media/audio/ui/KeypressStandard.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/Lock.ogg:system/media/audio/ui/Lock.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/LowBattery.ogg:system/media/audio/ui/LowBattery.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/Unlock.ogg:system/media/audio/ui/Unlock.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/VideoRecord.ogg:system/media/audio/ui/VideoRecord.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-1.flac:system/media/audio/ui/Volume-1.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-2.flac:system/media/audio/ui/Volume-2.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-3.flac:system/media/audio/ui/Volume-3.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-4.flac:system/media/audio/ui/Volume-4.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-5.flac:system/media/audio/ui/Volume-5.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-6.flac:system/media/audio/ui/Volume-6.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/Volume-7.flac:system/media/audio/ui/Volume-7.flac \
    vendor/moto/shamu/proprietary/media/audio/ui/WirelessChargingStarted.ogg:system/media/audio/ui/WirelessChargingStarted.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/camera_click.ogg:system/media/audio/ui/camera_click.ogg \
    vendor/moto/shamu/proprietary/media/audio/ui/media_volume.ogg:system/media/audio/ui/media_volume.ogg \
    vendor/moto/shamu/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/moto/shamu/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/moto/shamu/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/moto/shamu/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/moto/shamu/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/moto/shamu/proprietary/vendor/firmware/a420_pfp.fw:system/vendor/firmware/a420_pfp.fw \
    vendor/moto/shamu/proprietary/vendor/firmware/a420_pm4.fw:system/vendor/firmware/a420_pm4.fw \
    vendor/moto/shamu/proprietary/vendor/firmware/acdb.mbn:system/vendor/firmware/acdb.mbn \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b00:system/vendor/firmware/adsp.b00 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b01:system/vendor/firmware/adsp.b01 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b02:system/vendor/firmware/adsp.b02 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b03:system/vendor/firmware/adsp.b03 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b04:system/vendor/firmware/adsp.b04 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b05:system/vendor/firmware/adsp.b05 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b06:system/vendor/firmware/adsp.b06 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b07:system/vendor/firmware/adsp.b07 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b08:system/vendor/firmware/adsp.b08 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b10:system/vendor/firmware/adsp.b10 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b11:system/vendor/firmware/adsp.b11 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.b12:system/vendor/firmware/adsp.b12 \
    vendor/moto/shamu/proprietary/vendor/firmware/adsp.mdt:system/vendor/firmware/adsp.mdt \
    vendor/moto/shamu/proprietary/vendor/firmware/aonvr1.bin:system/vendor/firmware/aonvr1.bin \
    vendor/moto/shamu/proprietary/vendor/firmware/aonvr2.bin:system/vendor/firmware/aonvr2.bin \
    vendor/moto/shamu/proprietary/vendor/firmware/atmel-a432-14061601-0102aa-shamu-p1.tdat:system/vendor/firmware/atmel-a432-14061601-0102aa-shamu-p1.tdat \
    vendor/moto/shamu/proprietary/vendor/firmware/atmel-a432-14103001-0103aa-shamu.tdat:system/vendor/firmware/atmel-a432-14103001-0103aa-shamu.tdat \
    vendor/moto/shamu/proprietary/vendor/firmware/bcm20795_firmware.ncd:system/vendor/firmware/bcm20795_firmware.ncd \
    vendor/moto/shamu/proprietary/vendor/firmware/cy8c20247_24lkxi.hex:system/vendor/firmware/cy8c20247_24lkxi.hex \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.music.config:system/vendor/firmware/left.boost.music.config \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.music.eq:system/vendor/firmware/left.boost.music.eq \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost_music_table.preset:system/vendor/firmware/left.boost_music_table.preset \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost_n1b12.patch:system/vendor/firmware/left.boost_n1b12.patch \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost_n1c2.patch:system/vendor/firmware/left.boost_n1c2.patch \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.ringtone.config:system/vendor/firmware/left.boost.ringtone.config \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.ringtone.eq:system/vendor/firmware/left.boost.ringtone.eq \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost_ringtone_table.preset:system/vendor/firmware/left.boost_ringtone_table.preset \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.speaker:system/vendor/firmware/left.boost.speaker \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.voice.config:system/vendor/firmware/left.boost.voice.config \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost.voice.eq:system/vendor/firmware/left.boost.voice.eq \
    vendor/moto/shamu/proprietary/vendor/firmware/left.boost_voice_table.preset:system/vendor/firmware/left.boost_voice_table.preset \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.music.config:system/vendor/firmware/right.boost.music.config \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.music.eq:system/vendor/firmware/right.boost.music.eq \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost_music_table.preset:system/vendor/firmware/right.boost_music_table.preset \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost_n1b12.patch:system/vendor/firmware/right.boost_n1b12.patch \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost_n1c2.patch:system/vendor/firmware/right.boost_n1c2.patch \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.ringtone.config:system/vendor/firmware/right.boost.ringtone.config \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.ringtone.eq:system/vendor/firmware/right.boost.ringtone.eq \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost_ringtone_table.preset:system/vendor/firmware/right.boost_ringtone_table.preset \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.speaker:system/vendor/firmware/right.boost.speaker \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.voice.config:system/vendor/firmware/right.boost.voice.config \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost.voice.eq:system/vendor/firmware/right.boost.voice.eq \
    vendor/moto/shamu/proprietary/vendor/firmware/right.boost_voice_table.preset:system/vendor/firmware/right.boost_voice_table.preset \
    vendor/moto/shamu/proprietary/vendor/firmware/venus.b00:system/vendor/firmware/venus.b00 \
    vendor/moto/shamu/proprietary/vendor/firmware/venus.b01:system/vendor/firmware/venus.b01 \
    vendor/moto/shamu/proprietary/vendor/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/moto/shamu/proprietary/vendor/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/moto/shamu/proprietary/vendor/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/moto/shamu/proprietary/vendor/firmware/venus.mdt:system/vendor/firmware/venus.mdt \
    vendor/moto/shamu/proprietary/vendor/firmware/VRGain.bin:system/vendor/firmware/VRGain.bin \
    vendor/moto/shamu/proprietary/vendor/firmware/widevine.b00:system/vendor/firmware/widevine.b00 \
    vendor/moto/shamu/proprietary/vendor/firmware/widevine.b01:system/vendor/firmware/widevine.b01 \
    vendor/moto/shamu/proprietary/vendor/firmware/widevine.b02:system/vendor/firmware/widevine.b02 \
    vendor/moto/shamu/proprietary/vendor/firmware/widevine.b03:system/vendor/firmware/widevine.b03 \
    vendor/moto/shamu/proprietary/vendor/firmware/widevine.mdt:system/vendor/firmware/widevine.mdt \
    vendor/moto/shamu/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/moto/shamu/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
    vendor/moto/shamu/proprietary/vendor/lib/hw/activity_recognition.msm8084.so:system/vendor/lib/hw/activity_recognition.msm8084.so \
    vendor/moto/shamu/proprietary/vendor/lib/hw/flp.msm8084.so:system/vendor/lib/hw/flp.msm8084.so \
    vendor/moto/shamu/proprietary/vendor/lib/hw/sensors.msm8084.so:system/vendor/lib/hw/sensors.msm8084.so \
    vendor/moto/shamu/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/moto/shamu/proprietary/vendor/lib/soundfx/libspeakerbundle.so:system/vendor/lib/soundfx/libspeakerbundle.so \
    vendor/moto/shamu/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/moto/shamu/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/moto/shamu/proprietary/vendor/lib/libactuator_lc898122_camcorder.so:system/vendor/lib/libactuator_lc898122_camcorder.so \
    vendor/moto/shamu/proprietary/vendor/lib/libactuator_lc898122_camera.so:system/vendor/lib/libactuator_lc898122_camera.so \
    vendor/moto/shamu/proprietary/vendor/lib/libactuator_lc898122.so:system/vendor/lib/libactuator_lc898122.so \
    vendor/moto/shamu/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/moto/shamu/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/moto/shamu/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/moto/shamu/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/moto/shamu/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/moto/shamu/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/moto/shamu/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/moto/shamu/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/moto/shamu/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_ar0261_common.so:system/vendor/lib/libchromatix_ar0261_common.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_ar0261_cpp.so:system/vendor/lib/libchromatix_ar0261_cpp.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_ar0261_default_video.so:system/vendor/lib/libchromatix_ar0261_default_video.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_ar0261_liveshot.so:system/vendor/lib/libchromatix_ar0261_liveshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_ar0261_preview.so:system/vendor/lib/libchromatix_ar0261_preview.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_ar0261_snapshot.so:system/vendor/lib/libchromatix_ar0261_snapshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx132_common.so:system/vendor/lib/libchromatix_imx132_common.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx132_cpp.so:system/vendor/lib/libchromatix_imx132_cpp.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx132_default_video.so:system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx132_liveshot.so:system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx132_preview.so:system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_cpp.so:system/vendor/lib/libchromatix_imx135_cpp.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_liveshot.so:system/vendor/lib/libchromatix_imx135_liveshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_common.so:system/vendor/lib/libchromatix_imx214_common.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_cpp_snap.so:system/vendor/lib/libchromatix_imx214_cpp_snap.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_cpp.so:system/vendor/lib/libchromatix_imx214_cpp.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_default_video.so:system/vendor/lib/libchromatix_imx214_default_video.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_hfr_120.so:system/vendor/lib/libchromatix_imx214_hfr_120.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_hfr_60.so:system/vendor/lib/libchromatix_imx214_hfr_60.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_liveshot.so:system/vendor/lib/libchromatix_imx214_liveshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_preview.so:system/vendor/lib/libchromatix_imx214_preview.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_snapshot_hdr.so:system/vendor/lib/libchromatix_imx214_snapshot_hdr.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_snapshot.so:system/vendor/lib/libchromatix_imx214_snapshot.so \
    vendor/moto/shamu/proprietary/vendor/lib/libchromatix_imx214_video_hdr.so:system/vendor/lib/libchromatix_imx214_video_hdr.so \
    vendor/moto/shamu/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/moto/shamu/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/moto/shamu/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/moto/shamu/proprietary/vendor/lib/libcsd-client.so:system/vendor/lib/libcsd-client.so \
    vendor/moto/shamu/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    vendor/moto/shamu/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/moto/shamu/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/moto/shamu/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/moto/shamu/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/moto/shamu/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/moto/shamu/proprietary/vendor/lib/libfrsdk.so:system/vendor/lib/libfrsdk.so \
    vendor/moto/shamu/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/moto/shamu/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/moto/shamu/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    vendor/moto/shamu/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/moto/shamu/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/moto/shamu/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/moto/shamu/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/moto/shamu/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/moto/shamu/proprietary/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/moto/shamu/proprietary/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmdmcutback.so:system/vendor/lib/libmdmcutback.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_ar0261_eeprom.so:system/vendor/lib/libmmcamera_ar0261_eeprom.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_ar0261.so:system/vendor/lib/libmmcamera_ar0261.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_cac2_lib.so:system/vendor/lib/libmmcamera_cac2_lib.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_imx132.so:system/vendor/lib/libmmcamera_imx132.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_abf44.so:system/vendor/lib/libmmcamera_isp_abf44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_bcc44.so:system/vendor/lib/libmmcamera_isp_bcc44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_bf_scale_stats44.so:system/vendor/lib/libmmcamera_isp_bf_scale_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_bf_stats44.so:system/vendor/lib/libmmcamera_isp_bf_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_bpc44.so:system/vendor/lib/libmmcamera_isp_bpc44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_clf44.so:system/vendor/lib/libmmcamera_isp_clf44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_clf46.so:system/vendor/lib/libmmcamera_isp_clf46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_color_correct46.so:system/vendor/lib/libmmcamera_isp_color_correct46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_demosaic44.so:system/vendor/lib/libmmcamera_isp_demosaic44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_fovcrop_video46.so:system/vendor/lib/libmmcamera_isp_fovcrop_video46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_gamma44.so:system/vendor/lib/libmmcamera_isp_gamma44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder44.so:system/vendor/lib/libmmcamera_isp_scaler_encoder44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder46.so:system/vendor/lib/libmmcamera_isp_scaler_encoder46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_scaler_video46.so:system/vendor/lib/libmmcamera_isp_scaler_video46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_onsemi_cat24c16_eeprom.so:system/vendor/lib/libmmcamera_onsemi_cat24c16_eeprom.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    vendor/moto/shamu/proprietary/vendor/lib/libmotext_inf.so:system/vendor/lib/libmotext_inf.so \
    vendor/moto/shamu/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/moto/shamu/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/moto/shamu/proprietary/vendor/lib/libois_lc898122.so:system/vendor/lib/libois_lc898122.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmimotext.so:system/vendor/lib/libqmimotext.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/moto/shamu/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/moto/shamu/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    vendor/moto/shamu/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/moto/shamu/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/moto/shamu/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/moto/shamu/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/moto/shamu/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/moto/shamu/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    vendor/moto/shamu/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    vendor/moto/shamu/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/moto/shamu/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/moto/shamu/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/moto/shamu/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/moto/shamu/proprietary/vendor/lib/libsysutils_local.so:system/vendor/lib/libsysutils_local.so \
    vendor/moto/shamu/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/moto/shamu/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/moto/shamu/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/moto/shamu/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    vendor/moto/shamu/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/moto/shamu/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/moto/shamu/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/moto/shamu/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/lts_en_us_9_5_2b.raw:system/vendor/moto/audiomonitor/sensory/lts_en_us_9_5_2b.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_de_mfcc_16k_15_big_250_v3_4.raw:system/vendor/moto/audiomonitor/sensory/nn_de_mfcc_16k_15_big_250_v3_4.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_en_uk_mfcc_16k_15_big_250_v2_2.raw:system/vendor/moto/audiomonitor/sensory/nn_en_uk_mfcc_16k_15_big_250_v2_2.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_en_us_mfcc_16k_15_big_250_v5_1_1.raw:system/vendor/moto/audiomonitor/sensory/nn_en_us_mfcc_16k_15_big_250_v5_1_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_es_es_mfcc_16k_15_big_250_v1_5.raw:system/vendor/moto/audiomonitor/sensory/nn_es_es_mfcc_16k_15_big_250_v1_5.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_es_us_mfcc_16k_15_big_250_v1_5.raw:system/vendor/moto/audiomonitor/sensory/nn_es_us_mfcc_16k_15_big_250_v1_5.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_fr_ca_mfcc_16k_15_big_250_v2_5.raw:system/vendor/moto/audiomonitor/sensory/nn_fr_ca_mfcc_16k_15_big_250_v2_5.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_fr_fr_mfcc_16k_15_big_250_v2_4.raw:system/vendor/moto/audiomonitor/sensory/nn_fr_fr_mfcc_16k_15_big_250_v2_4.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_it_mfcc_16k_15_big_250_v3_5.raw:system/vendor/moto/audiomonitor/sensory/nn_it_mfcc_16k_15_big_250_v3_5.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/nn_pt_mfcc_16k_15_big_250_v1_1.raw:system/vendor/moto/audiomonitor/sensory/nn_pt_mfcc_16k_15_big_250_v1_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_dede_1_1.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_dede_1_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_enuk_1_1.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_enuk_1_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_enus_2_0.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_enus_2_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_eses_1_2.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_eses_1_2.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_esus_1_2.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_esus_1_2.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_frca_prec1_1_0.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_frca_prec1_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_frfr_1_1.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_frfr_1_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_it_it_1_0.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_it_it_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/phonemesearch_ptbr_1_0.raw:system/vendor/moto/audiomonitor/sensory/phonemesearch_ptbr_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_dede_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_dede_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_enuk_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_enuk_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_enus_2_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_enus_2_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_eses_1_2.raw:system/vendor/moto/audiomonitor/sensory/svsid_eses_1_2.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_esus_1_2.raw:system/vendor/moto/audiomonitor/sensory/svsid_esus_1_2.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_frca_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_frca_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_frfr_1_1.raw:system/vendor/moto/audiomonitor/sensory/svsid_frfr_1_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_it_it_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_it_it_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_ptbr_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_ptbr_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_dede_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_dede_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_enuk_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_enuk_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_eses_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_eses_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_itit_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn1_itit_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn_enus_3_1.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn_enus_3_1.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn_frfr_1_0.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn_frfr_1_0.raw \
    vendor/moto/shamu/proprietary/vendor/moto/audiomonitor/sensory/svsid_triggerogn_ptbr_2_1.raw:system/vendor/moto/audiomonitor/sensory/svsid_triggerogn_ptbr_2_1.raw \
    vendor/moto/shamu/proprietary/vendor/xbin/wlutil:system/vendor/xbin/wlutil
